VINDRC_GEN = '''" This .vindrc is generated by runtime test.
set listen_interval=0.1
set initmode=i
set winresizer_initmode=0

inoremap <f12> <to_gui_normal>
noremap <f12> <to_gui_normal>

noremap : <to_command>
inoremap : <to_command>

noremap winresizer <c-w>e
noremap <lalt><lalt> <to_edi_normal>

map <alt-b><alt-j> {Hello World!<cr>}
map <f11><ctrl-q> <alt-j>
map <f10><tab> <alt-b>
map <f7><f7> <f10><tab><f11><ctrl-q>
'''
