VINDRC_GEN = '''" This .vindrc is generated by runtime test.
set listen_interval=0.1
set initmode=i
inoremap <f12> <to_gui_normal>
noremap <f12> <to_gui_normal>

noremap : <to_command>
inoremap : <to_command>
'''
