#ifndef _VIRTUAL_KEY_FWD_HPP
#define _VIRTUAL_KEY_FWD_HPP

#define VKC_MOUSE_LEFT   (static_cast<unsigned char>(1))
#define VKC_MOUSE_RIGHT  (static_cast<unsigned char>(2))
#define VKC_MOUSE_MID    (static_cast<unsigned char>(4))

#define VKC_0            (static_cast<unsigned char>(48))
#define VKC_1            (static_cast<unsigned char>(49))
#define VKC_2            (static_cast<unsigned char>(50))
#define VKC_3            (static_cast<unsigned char>(51))
#define VKC_4            (static_cast<unsigned char>(52))
#define VKC_5            (static_cast<unsigned char>(53))
#define VKC_6            (static_cast<unsigned char>(54))
#define VKC_7            (static_cast<unsigned char>(55))
#define VKC_8            (static_cast<unsigned char>(56))
#define VKC_9            (static_cast<unsigned char>(57))

#define VKC_MINUS        (static_cast<unsigned char>(189))
#define VKC_HAT          (static_cast<unsigned char>(222))
#define VKC_VBAR         (static_cast<unsigned char>(220))
#define VKC_BKSPACE      (static_cast<unsigned char>(8))

#define VKC_TAB          (static_cast<unsigned char>(9))
#define VKC_Q            (static_cast<unsigned char>(81))
#define VKC_W            (static_cast<unsigned char>(87))
#define VKC_E            (static_cast<unsigned char>(69))
#define VKC_R            (static_cast<unsigned char>(82))
#define VKC_T            (static_cast<unsigned char>(84))
#define VKC_Y            (static_cast<unsigned char>(89))
#define VKC_U            (static_cast<unsigned char>(85))
#define VKC_I            (static_cast<unsigned char>(73))
#define VKC_O            (static_cast<unsigned char>(79))
#define VKC_P            (static_cast<unsigned char>(80))
#define VKC_AT           (static_cast<unsigned char>(192))
#define VKC_LBOX_BRACKET (static_cast<unsigned char>(219))
#define VKC_ENTER        (static_cast<unsigned char>(13))

#define VKC_CAPSLOCK     (static_cast<unsigned char>(240))
#define VKC_A            (static_cast<unsigned char>(65))
#define VKC_S            (static_cast<unsigned char>(83))
#define VKC_D            (static_cast<unsigned char>(68))
#define VKC_F            (static_cast<unsigned char>(70))
#define VKC_G            (static_cast<unsigned char>(71))
#define VKC_H            (static_cast<unsigned char>(72))
#define VKC_J            (static_cast<unsigned char>(74))
#define VKC_K            (static_cast<unsigned char>(75))
#define VKC_L            (static_cast<unsigned char>(76))
#define VKC_PLUS         (static_cast<unsigned char>(187))
#define VKC_COLON        (static_cast<unsigned char>(186))
#define VKC_RBOX_BRACKET (static_cast<unsigned char>(221))

#define VKC_LSHIFT       (static_cast<unsigned char>(160))
#define VKC_Z            (static_cast<unsigned char>(90))
#define VKC_X            (static_cast<unsigned char>(88))
#define VKC_C            (static_cast<unsigned char>(67))
#define VKC_V            (static_cast<unsigned char>(86))
#define VKC_B            (static_cast<unsigned char>(66))
#define VKC_N            (static_cast<unsigned char>(78))
#define VKC_M            (static_cast<unsigned char>(77))

#define VKC_COMMA        (static_cast<unsigned char>(188))
#define VKC_PERIOD       (static_cast<unsigned char>(190))
#define VKC_SLASH        (static_cast<unsigned char>(191))
#define VKC_BKSLASH      (static_cast<unsigned char>(226))
#define VKC_RSHIFT       (static_cast<unsigned char>(161))

#define VKC_LCTRL        (static_cast<unsigned char>(162))
#define VKC_LWIN         (static_cast<unsigned char>(91))
#define VKC_RWIN         (static_cast<unsigned char>(92))
#define VKC_LALT         (static_cast<unsigned char>(164))
#define VKC_NOCONVERT    (static_cast<unsigned char>(29))
#define VKC_SPACE        (static_cast<unsigned char>(32))
#define VKC_CONVERT      (static_cast<unsigned char>(28))
#define VKC_KANA         (static_cast<unsigned char>(242))
#define VKC_RALT         (static_cast<unsigned char>(165))
#define VKC_APP          (static_cast<unsigned char>(93))
#define VKC_RCTRL        (static_cast<unsigned char>(163))

#define VKC_ESC          (static_cast<unsigned char>(27))
#define VKC_F1           (static_cast<unsigned char>(112))
#define VKC_F2           (static_cast<unsigned char>(113))
#define VKC_F3           (static_cast<unsigned char>(114))
#define VKC_F4           (static_cast<unsigned char>(115))
#define VKC_F5           (static_cast<unsigned char>(116))
#define VKC_F6           (static_cast<unsigned char>(117))
#define VKC_F7           (static_cast<unsigned char>(118))
#define VKC_F8           (static_cast<unsigned char>(119))
#define VKC_F9           (static_cast<unsigned char>(120))
#define VKC_F10          (static_cast<unsigned char>(121))
#define VKC_F11          (static_cast<unsigned char>(122))
#define VKC_F12          (static_cast<unsigned char>(123))
#define VKC_F13          (static_cast<unsigned char>(124))
#define VKC_F14          (static_cast<unsigned char>(125))
#define VKC_F15          (static_cast<unsigned char>(126))
#define VKC_F16          (static_cast<unsigned char>(127))
#define VKC_F17          (static_cast<unsigned char>(128))
#define VKC_F18          (static_cast<unsigned char>(129))
#define VKC_F19          (static_cast<unsigned char>(130))
#define VKC_F20          (static_cast<unsigned char>(131))
#define VKC_F21          (static_cast<unsigned char>(132))
#define VKC_F22          (static_cast<unsigned char>(133))
#define VKC_F23          (static_cast<unsigned char>(134))
#define VKC_F24          (static_cast<unsigned char>(135))

#define VKC_SNAPSHOT     (static_cast<unsigned char>(44))
#define VKC_SCROLL       (static_cast<unsigned char>(145))
#define VKC_PAUSE        (static_cast<unsigned char>(19))
#define VKC_INSERT       (static_cast<unsigned char>(45))
#define VKC_HOME         (static_cast<unsigned char>(36))
#define VKC_PAGEUP       (static_cast<unsigned char>(33))
#define VKC_DELETE       (static_cast<unsigned char>(46))
#define VKC_END          (static_cast<unsigned char>(35))
#define VKC_PAGEDOWN     (static_cast<unsigned char>(34))

#define VKC_LEFT         (static_cast<unsigned char>(37))
#define VKC_UP           (static_cast<unsigned char>(38))
#define VKC_RIGHT        (static_cast<unsigned char>(39))
#define VKC_DOWN         (static_cast<unsigned char>(40))

#define VKC_NUMLOCK      (static_cast<unsigned char>(144))

#define VKC_FROM_JP      (static_cast<unsigned char>(244))
#define VKC_TO_EN        (static_cast<unsigned char>(243))
#define VKC_FROM_EN      (static_cast<unsigned char>(243))
#define VKC_TO_JP        (static_cast<unsigned char>(244))
#define VKC_IME          (static_cast<unsigned char>(14))

#define VKC_WIN          (static_cast<unsigned char>(15))
#define VKC_SHIFT        (static_cast<unsigned char>(16))
#define VKC_CTRL         (static_cast<unsigned char>(17))
#define VKC_ALT          (static_cast<unsigned char>(18))
#define VKC_OPTIONAL     (static_cast<unsigned char>(177))
#define VKC_OPTNUMBER    (static_cast<unsigned char>(178))

#endif
