#ifndef _VIRTUAL_KEY_FWD_HPP
#define _VIRTUAL_KEY_FWD_HPP

#define VKC_FROM_JP      (244)
#define VKC_TO_EN        (243)
#define VKC_FROM_EN      (243)
#define VKC_TO_JP        (244)

#define VKC_0            (48)
#define VKC_1            (49)
#define VKC_2            (50)
#define VKC_3            (51)
#define VKC_4            (52)
#define VKC_5            (53)
#define VKC_6            (54)
#define VKC_7            (55)
#define VKC_8            (56)
#define VKC_9            (57)

#define VKC_MINUS        (189)
#define VKC_HAT          (222)
#define VKC_VBAR         (220)
#define VKC_BKSPACE      (8)

#define VKC_TAB          (9)
#define VKC_Q            (81)
#define VKC_W            (87)
#define VKC_E            (69)
#define VKC_R            (82)
#define VKC_T            (84)
#define VKC_Y            (89)
#define VKC_U            (85)
#define VKC_I            (73)
#define VKC_O            (79)
#define VKC_P            (80)
#define VKC_AT           (192)
#define VKC_LBOX_BRACKET (219)
#define VKC_ENTER        (13)

#define VKC_CAPS_LOCK    (240)
#define VKC_A            (65)
#define VKC_S            (83)
#define VKC_D            (68)
#define VKC_F            (70)
#define VKC_G            (71)
#define VKC_H            (72)
#define VKC_J            (74)
#define VKC_K            (75)
#define VKC_L            (76)
#define VKC_PLUS         (187)
#define VKC_COLON        (186)
#define VKC_RBOX_BRACKET (221)

#define VKC_LSHIFT       (160)
#define VKC_Z            (90)
#define VKC_X            (88)
#define VKC_C            (67)
#define VKC_V            (86)
#define VKC_B            (66)
#define VKC_N            (78)
#define VKC_M            (77)

#define VKC_COMMA        (188)
#define VKC_PERIOD       (190)
#define VKC_SLASH        (191)
#define VKC_BKSLASH      (226)
#define VKC_RSHIFT       (161)

#define VKC_LCTRL        (162)
#define VKC_LWIN         (91)
#define VKC_RWIN         (92)
#define VKC_LALT         (164)
#define VKC_NOCONVERT    (29)
#define VKC_SPACE        (32)
#define VKC_CONVERT      (28)
#define VKC_KANA         (242)
#define VKC_RALT         (165)
#define VKC_APP          (93)
#define VKC_RCTRL        (163)

#define VKC_ESC          (27)
#define VKC_F1           (112)
#define VKC_F2           (113)
#define VKC_F3           (114)
#define VKC_F4           (115)
#define VKC_F5           (116)
#define VKC_F6           (117)
#define VKC_F7           (118)
#define VKC_F8           (119)
#define VKC_F9           (120)
#define VKC_F10          (121)
#define VKC_F11          (122)
#define VKC_F12          (123)
#define VKC_F13          (124)
#define VKC_F14          (125)
#define VKC_F15          (126)
#define VKC_F16          (127)
#define VKC_F17          (128)
#define VKC_F18          (129)
#define VKC_F19          (130)
#define VKC_F20          (131)
#define VKC_F21          (132)
#define VKC_F22          (133)
#define VKC_F23          (134)
#define VKC_F24          (135)

#define VKC_SNAPSHOT     (44)
#define VKC_SCROLL       (145)
#define VKC_PAUSE        (19)
#define VKC_INSERT       (45)
#define VKC_HOME         (36)
#define VKC_PAGEUP       (33)
#define VKC_DELETE       (46)
#define VKC_END          (35)
#define VKC_PAGEDOWN     (34)

#define VKC_LEFT         (37)
#define VKC_UP           (38)
#define VKC_RIGHT        (39)
#define VKC_DOWN         (40)

#define VKC_NUMLOCK      (144)

#define VKC_OPTIONAL     (177)

#endif