name: MinGW build

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'src/**'
      - '.github/**'
      - 'tests/**'
      - 'tools/**'

  pull_request:
    branches:
      - master
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'src/**'
      - '.github/**'
      - 'tests/**'
      - 'tools/**'


jobs:
  x64:
    runs-on: windows-2019

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Setup Dependencies
      shell: powershell
      run: |
        choco install -y 7zip.install
        curl.exe -OL https://github.com/niXman/mingw-builds-binaries/releases/download/13.2.0-rt_v11-rev0/x86_64-13.2.0-release-win32-seh-msvcrt-rt_v11-rev0.7z
        7z x x86_64-13.2.0-release-win32-seh-msvcrt-rt_v11-rev0.7z

    - name: Configure CMake
      run: |
        cmake -B debug -DCMAKE_BUILD_TYPE=Debug -G "MinGW Makefiles" -DCCACHE_ENABLE=OFF .
      env:
        CC: ${{github.workspace}}/mingw64/bin/gcc.exe
        CXX: ${{github.workspace}}/mingw64/bin/g++.exe

    - name: Build
      run: |
        cmake --build debug --config Debug
      env:
        CC: ${{github.workspace}}/mingw64/bin/gcc.exe
        CXX: ${{github.workspace}}/mingw64/bin/g++.exe
