name: test

on:
  push:
    branches: [ master ]
    tags:
      - v*.*.*
      - test*
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'src/**'
      - 'tests/**'
      - '.github/**'
      - 'tools/**'

  pull_request:
    branches: [ master ]
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'src/**'
      - '.github/**'
      - 'tests/**'
      - 'tools/**'

env:
  BUILD_TYPE: Debug

jobs:
  test-on-Windows:
    runs-on: windows-2019

    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      working-directory: ${{github.workspace}}/tests
      run: |
        cmake -B build_msvc unit

    - name: Build
      working-directory: ${{github.workspace}}/tests
      run: |
        cmake --build build_msvc --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/tests
      run: |
        ctest -C ${{env.BUILD_TYPE}} --test-dir build_msvc --output-on-failure
